- name: Deploy Docker container to remote server
  hosts: web
  become: yes
  tasks:
    - name: Copy app code to server
      copy:
        src: ../docker/
        dest: /home/ubuntu/myapp/

    - name: Build Docker image
      shell: docker build -t myapp /home/ubuntu/myapp

    - name: Stop existing container
      shell: docker rm -f myapp || true

    - name: Run container
      shell: docker run -d -p 5000:5000 --name myapp myapp

